__all__ = [
    "DEFAULT_UNK_TOKEN",
    "DEFAULT_SEP_TOKEN",
    "DEFAULT_PAD_TOKEN",
    "DEFAULT_CLS_TOKEN",
    "DEFAULT_MASK_TOKEN",
    "DEFAULT_BOS_TOKEN",
    "DEFAULT_EOS_TOKEN",
]

DEFAULT_UNK_TOKEN: str = "[UNK]"
DEFAULT_SEP_TOKEN: str = "[SEP]"
DEFAULT_PAD_TOKEN: str = "[PAD]"
DEFAULT_CLS_TOKEN: str = "[CLS]"
DEFAULT_MASK_TOKEN: str = "[MASK]"
DEFAULT_BOS_TOKEN: str = "<s>"
DEFAULT_EOS_TOKEN: str = "</s>"
