# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: check-symlinks
      - id: destroyed-symlinks
      - id: trailing-whitespace
        exclude: |
          (?x)(
            ^data/
          )
      - id: end-of-file-fixer
        exclude: |
          (?x)(
            ^data/
          )
      - id: check-yaml
      - id: check-toml
      - id: check-ast
      - id: check-added-large-files
        exclude: |
          (?x)(
            ^data/
          )
      - id: check-merge-conflict
      - id: check-executables-have-shebangs
      - id: check-shebang-scripts-are-executable
      - id: detect-private-key
      - id: debug-statements
  - repo: https://github.com/psf/black
    rev: 24.10.0
    hooks:
      - id: black-jupyter
  - repo: https://github.com/asottile/pyupgrade
    rev: v3.19.1
    hooks:
      - id: pyupgrade
        args: [--py38-plus] # sync with requires-python
  - repo: https://github.com/PyCQA/autoflake
    rev: v2.3.1
    hooks:
      - id: autoflake
        args: [--remove-all-unused-imports, --in-place, --ignore-init-module-imports, --remove-duplicate-keys, --remove-unused-variables]
  - repo: https://github.com/codespell-project/codespell
    rev: v2.3.0
    hooks:
      - id: codespell
        additional_dependencies: [".[toml]"]
        exclude: |
          (?x)(
            ^data/
          )
