train_config:
  output_dir: ./output/finetune/charge
  logging_dir: ./output/finetune/charge/logs
  learning_rate: 5e-5
  train_batch_size: 8
  eval_batch_size: 8
  epochs: 3
  weight_decay: 0.01
  eval_strategy: "steps"
  eval_steps: 500
  save_strategy: "epoch"
  enable_wandb: false
  run_name: "charge_run"
  wandb_project: "charge-prediction"
  extra_model_kwargs: {}
  extra_tokenizer_kwargs: {}
  model_max_length: 512
  charge_num: 321
